# Generated by Django 6.0.2 on 2026-02-07 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(help_text='Auto-filled from Employer Profile if left blank', max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='Key skills required')),
                ('location', models.CharField(max_length=100)),
                ('salary_range', models.CharField(blank=True, help_text='e.g. $50k - $70k', max_length=100)),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('FL', 'Freelance'), ('IN', 'Internship')], default='FT', max_length=2)),
                ('remote_status', models.CharField(choices=[('ON', 'On-site'), ('RE', 'Remote'), ('HY', 'Hybrid')], default='ON', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
