# Generated by Django 6.0.2 on 2026-02-07 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
