# Generated by Django 6.0.2 on 2026-02-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Last date to apply', null=True),
        ),
    ]
