# Generated by Django 6.0.2 on 2026-02-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload PDF resume', null=True, upload_to='resumes/%Y/%m/%d/'),
        ),
    ]
