# Generated by Django 6.0.2 on 2026-02-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Junior', 'Junior (0-2 years)'), ('Mid', 'Mid-Level (2-5 years)'), ('Senior', 'Senior (5+ years)'), ('Lead', 'Lead / Manager')], default='Mid', max_length=20),
        ),
    ]
