# Generated by Django 6.0.2 on 2026-02-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(default=0, help_text='Numeric value for sorting/filtering'),
        ),
    ]
