# Generated by Django 6.0.2 on 2026-02-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_candidateprofile_id_alter_employerprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
